"""Generate paper tables and figures from the full 640k STATS19 results.

Usage: run after `bash run_full_all.sh` completes. Reads
`results_full_final/summary_metrics.csv` and produces:

  - paper_tables/table_main_results.tex   (Table 2, main results)
  - paper_tables/table_temporal_gap.tex   (Table 3, temporal degradation)
  - paper_tables/dataset_stats.tex        (Table 1)
  - paper_overleaf/figures/dataset_stats.{png,pdf}
  - paper_overleaf/figures/temporal_drop.{png,pdf}
  - paper_overleaf/figures/sensitivity_panels.{png,pdf} (unchanged pass-through)

The script is idempotent: it only writes if the summary file exists.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

ROOT = Path(__file__).resolve().parent
SRC = ROOT / "results_full_final"
FIGDIR = ROOT / "paper_overleaf" / "figures"
TABDIR = ROOT / "paper_tables"
FIGDIR.mkdir(parents=True, exist_ok=True)
TABDIR.mkdir(parents=True, exist_ok=True)


def _fmt(mean, std, digits=4):
    m = f"{mean:.{digits}f}"
    if std is None or pd.isna(std):
        return m
    return f"{m} $\\pm${std:.{digits}f}"


def build_main_table() -> None:
    """Table 2: main results across random/group/temporal for all methods."""
    summary = pd.read_csv(SRC / "summary_metrics.csv", header=[0, 1])
    # Flatten the multi-index columns
    summary.columns = [
        "_".join([str(x) for x in c if x and not str(x).startswith("Unnamed")]).strip("_")
        for c in summary.columns
    ]
    summary = summary.rename(columns={"": "split", "split_": "split", "method_": "method"})
    # find split and method columns
    split_col = [c for c in summary.columns if c.startswith("split") and "_" not in c[5:]][0]
    method_col = [c for c in summary.columns if c.startswith("method") and "_" not in c[6:]][0]

    order = [
        "LightGBM_raw", "RACE_MCBM_local_density", "RACE_MCBM_optimized",
        "RACE_CBM_plain", "RACE_MCBM_reporting_aware", "SHAP_top48_LR",
        "LR_raw", "LR_actionable_only",
    ]
    splits = ["random", "group", "temporal"]

    rows = []
    for split in splits:
        for m in order:
            r = summary[(summary[split_col] == split) & (summary[method_col] == m)]
            if r.empty:
                continue
            def g(metric):
                mean_c = f"{metric}_mean"
                std_c = f"{metric}_std"
                if mean_c not in summary.columns:
                    return None, None
                return float(r[mean_c].iloc[0]), (float(r[std_c].iloc[0]) if std_c in summary.columns else None)
            f1_m, f1_s = g("f1")
            roc_m, roc_s = g("roc_auc")
            pr_m, pr_s = g("pr_auc")
            brier_m, brier_s = g("brier")
            ncc_m, ncc_s = g("ncc")
            art_m, art_s = g("artifact_score")
            rows.append({
                "split": split,
                "method": m,
                "f1": _fmt(f1_m, f1_s),
                "roc": _fmt(roc_m, roc_s),
                "pr": _fmt(pr_m, pr_s),
                "brier": f"{brier_m:.4f}" if brier_m is not None else "--",
                "ncc": f"{ncc_m:.2f}" if (ncc_m is not None and not np.isnan(ncc_m)) else "--",
                "art": f"{art_m:.4f}" if (art_m is not None and not np.isnan(art_m)) else "--",
            })

    lines = [
        "% Auto-generated by make_paper_tables_full.py",
        "\\begin{tabular}{llrrrrrr}",
        "\\hline",
        "\\textbf{Split} & \\textbf{Method} & \\textbf{F1} & \\textbf{ROC-AUC} & \\textbf{PR-AUC} & \\textbf{Brier} & \\textbf{NCC} & \\textbf{Artifact} \\\\",
        "\\hline",
    ]
    last_split = None
    for r in rows:
        prefix = r["split"] if r["split"] != last_split else ""
        lines.append(
            f"{prefix} & \\texttt{{{r['method']}}} & {r['f1']} & {r['roc']} & {r['pr']} & {r['brier']} & {r['ncc']} & {r['art']} \\\\"
        )
        if r["split"] != last_split and last_split is not None:
            pass
        last_split = r["split"]
    lines.append("\\hline")
    lines.append("\\end{tabular}")
    (TABDIR / "table_main_results.tex").write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {TABDIR / 'table_main_results.tex'}")


def build_temporal_gap() -> None:
    """Table 3: temporal degradation Δ_temp = F1_random - F1_temporal."""
    summary = pd.read_csv(SRC / "summary_metrics.csv", header=[0, 1])
    summary.columns = [
        "_".join([str(x) for x in c if x and not str(x).startswith("Unnamed")]).strip("_")
        for c in summary.columns
    ]
    split_col = [c for c in summary.columns if c.startswith("split") and "_" not in c[5:]][0]
    method_col = [c for c in summary.columns if c.startswith("method") and "_" not in c[6:]][0]

    methods = [
        "RACE_MCBM_local_density", "RACE_MCBM_reporting_aware",
        "LightGBM_raw", "SHAP_top48_LR", "RACE_CBM_plain", "LR_raw",
    ]
    lines = [
        "\\begin{tabular}{lrr}",
        "\\hline",
        "\\textbf{Method} & \\textbf{F1 Random} & $\\Delta_{\\text{temp}}$ \\\\",
        "\\hline",
    ]
    for m in methods:
        r_rand = summary[(summary[split_col] == "random") & (summary[method_col] == m)]
        r_temp = summary[(summary[split_col] == "temporal") & (summary[method_col] == m)]
        if r_rand.empty or r_temp.empty:
            continue
        f1_r = float(r_rand["f1_mean"].iloc[0])
        f1_t = float(r_temp["f1_mean"].iloc[0])
        delta = f1_r - f1_t
        lines.append(f"\\texttt{{{m}}} & {f1_r:.4f} & {delta:+.4f} \\\\")
    lines.append("\\hline")
    lines.append("\\end{tabular}")
    (TABDIR / "table_temporal_gap.tex").write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {TABDIR / 'table_temporal_gap.tex'}")


def build_dataset_stats_table() -> None:
    """Table 1: per-year counts and KSI rates on the FULL 640k data."""
    df = pd.read_csv(ROOT / "data" / "processed" / "stats19_multi_year_raw.csv",
                     usecols=["collision_year", "target"], low_memory=False)
    g = df.groupby("collision_year").agg(records=("target", "size"), ksi=("target", "sum"))
    g["rate"] = g["ksi"] / g["records"]
    lines = [
        "\\begin{tabular}{lrrr}",
        "\\hline",
        "\\textbf{Year} & \\textbf{Records} & \\textbf{KSI Count} & \\textbf{KSI Rate} \\\\",
        "\\hline",
    ]
    for y, row in g.iterrows():
        lines.append(f"{int(y)} & {int(row['records']):,} & {int(row['ksi']):,} & {row['rate']*100:.1f}\\% \\\\")
    total = df.shape[0]; ksi = int(df['target'].sum())
    lines.append("\\hline")
    lines.append(f"\\textbf{{Total}} & \\textbf{{{total:,}}} & \\textbf{{{ksi:,}}} & \\textbf{{{ksi/total*100:.1f}\\%}} \\\\")
    lines.append("\\hline")
    lines.append("\\end{tabular}")
    (TABDIR / "dataset_stats.tex").write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {TABDIR / 'dataset_stats.tex'}")


def build_temporal_drop_figure() -> None:
    """Figure: random vs temporal F1 per method."""
    summary = pd.read_csv(SRC / "summary_metrics.csv", header=[0, 1])
    summary.columns = [
        "_".join([str(x) for x in c if x and not str(x).startswith("Unnamed")]).strip("_")
        for c in summary.columns
    ]
    split_col = [c for c in summary.columns if c.startswith("split") and "_" not in c[5:]][0]
    method_col = [c for c in summary.columns if c.startswith("method") and "_" not in c[6:]][0]

    order = [
        "LightGBM_raw", "RACE_MCBM_local_density", "RACE_MCBM_reporting_aware",
        "SHAP_top48_LR", "RACE_CBM_plain", "RACE_MCBM_optimized", "LR_raw",
    ]
    colours = {
        "LightGBM_raw": "#666666",
        "RACE_MCBM_local_density": "#0072B2",
        "RACE_MCBM_reporting_aware": "#009E73",
        "SHAP_top48_LR": "#CC79A7",
        "RACE_CBM_plain": "#E69F00",
        "RACE_MCBM_optimized": "#D55E00",
        "LR_raw": "#8B4513",
    }

    rows = []
    for m in order:
        r_rand = summary[(summary[split_col] == "random") & (summary[method_col] == m)]
        r_temp = summary[(summary[split_col] == "temporal") & (summary[method_col] == m)]
        if r_rand.empty or r_temp.empty:
            continue
        rows.append((m, float(r_rand["f1_mean"].iloc[0]), float(r_temp["f1_mean"].iloc[0])))

    methods = [x[0] for x in rows]
    rnd = np.array([x[1] for x in rows])
    tmp = np.array([x[2] for x in rows])
    cs = [colours[m] for m in methods]

    x = np.arange(len(methods))
    width = 0.36
    fig, ax = plt.subplots(figsize=(10.5, 4.2))
    ax.bar(x - width / 2, rnd, width, color=cs, alpha=0.55, label="Random F1")
    ax.bar(x + width / 2, tmp, width, color=cs, alpha=0.95, label="Temporal F1")
    for xi, r, t in zip(x, rnd, tmp):
        drop = r - t
        y_top = max(r, t) + 0.015
        ax.text(xi, y_top, f"$\\Delta$={drop:+.3f}", ha="center", va="bottom", fontsize=8)
    ax.set_xticks(x)
    ax.set_xticklabels(methods, rotation=25, ha="right")
    ax.set_ylabel("F1")
    ax.set_ylim(0.0, 0.60)
    ax.set_title("Temporal generalisation: random-split F1 vs 2024 temporal-split F1 (full 640k)")
    ax.legend(frameon=False, loc="upper right")
    ax.grid(True, axis="y", alpha=0.25)
    plt.tight_layout()
    plt.savefig(FIGDIR / "temporal_drop.png", dpi=300, bbox_inches="tight")
    plt.savefig(FIGDIR / "temporal_drop.pdf", bbox_inches="tight")
    plt.close()
    print(f"Wrote {FIGDIR / 'temporal_drop.png/.pdf'}")


def build_dataset_stats_figure() -> None:
    """Figure 2 with actual 640k per-year counts."""
    df = pd.read_csv(ROOT / "data" / "processed" / "stats19_multi_year_raw.csv",
                     usecols=["collision_year", "target"], low_memory=False)
    years = sorted(df["collision_year"].dropna().astype(int).unique().tolist())
    counts = [int((df["collision_year"] == y).sum()) for y in years]
    ksi_rate = [float(df.loc[df["collision_year"] == y, "target"].mean()) for y in years]

    import sys
    src = ROOT / "src"
    if str(src) not in sys.path:
        sys.path.insert(0, str(src))
    from race_mcbm.taxonomy import build_taxonomy
    cols = [c for c in pd.read_csv(ROOT / "data" / "processed" / "stats19_multi_year_raw.csv",
                                    nrows=1).columns if c not in ("target", "collision_year")]
    tax = build_taxonomy(cols, ROOT / "configs" / "artifact_taxonomy.yaml")
    a = tax.artifact_score.reindex(cols).fillna(0.0).to_numpy(dtype=float)

    fig, axes = plt.subplots(1, 2, figsize=(11.0, 3.6))
    ax = axes[0]
    bars = ax.bar(years, counts, color="#0072B2", width=0.6)
    ax.set_xlabel("Year"); ax.set_ylabel("Records", color="#0072B2")
    ax.tick_params(axis="y", labelcolor="#0072B2")
    ax.set_xticks(years)
    ax2 = ax.twinx()
    ax2.plot(years, ksi_rate, marker="o", color="#E69F00", linewidth=2)
    ax2.set_ylabel("KSI rate", color="#E69F00")
    ax2.tick_params(axis="y", labelcolor="#E69F00")
    ax2.set_ylim(0.10, 0.28)
    for b, c in zip(bars, counts):
        ax.text(b.get_x() + b.get_width() / 2, c + max(counts) * 0.01, f"{c:,}",
                ha="center", va="bottom", fontsize=8)
    ax.set_title("(a) Records and KSI rate by year")
    ax.grid(True, axis="y", alpha=0.25)

    bins = [0.0, 0.05, 0.35, 0.55, 0.9, 1.05]
    labels = ["safety\n(0.0)", "low\n(0.0-0.35)", "structural\n(0.35-0.55)",
              "unknown\n(0.55-0.9)", "reporting\n(0.9-1.0)"]
    hist, _ = np.histogram(a, bins=bins)
    axes[1].bar(range(len(hist)), hist,
                color=["#009E73", "#0072B2", "#CC79A7", "#E69F00", "#D55E00"])
    axes[1].set_xticks(range(len(hist)))
    axes[1].set_xticklabels(labels, fontsize=8)
    axes[1].set_ylabel("Feature count")
    axes[1].set_title(f"(b) Artifact score distribution over {len(a)} features")
    axes[1].grid(True, axis="y", alpha=0.25)
    for i, h in enumerate(hist):
        axes[1].text(i, h + max(hist) * 0.01, str(int(h)), ha="center", va="bottom", fontsize=9)

    plt.tight_layout()
    plt.savefig(FIGDIR / "dataset_stats.png", dpi=300, bbox_inches="tight")
    plt.savefig(FIGDIR / "dataset_stats.pdf", bbox_inches="tight")
    plt.close()
    print(f"Wrote {FIGDIR / 'dataset_stats.png/.pdf'}")


if __name__ == "__main__":
    build_dataset_stats_table()
    build_dataset_stats_figure()
    if (SRC / "summary_metrics.csv").exists():
        build_main_table()
        build_temporal_gap()
        build_temporal_drop_figure()
    else:
        print(f"NOTE: {SRC / 'summary_metrics.csv'} not found yet. Run experiments first.")
